popular_airports = {"Alabama": "Birmingham-Shuttlesworth International Airport",
                    "Alaska": "Fairbanks International Airport",
                    "Arizona": "Phoenix Sky Harbor International Airport",
                    "Arkansas": "Adams Field", "California": "San Diego International Airport",
                    "Colorado": "Denver International Airport", "Connecticut": "Bradley International Airport",
                    "Delaware": "New Castle Airport",
                    "Florida": "Orlando International Airport",
                    "Georgia": "Hartsfield Jackson Atlanta International Airport",
                    "Hawaii": "Honolulu International Airport", "Idaho": "Boise Air Terminal/Gowen field",
                    "Illinois": "Chicago Midway International Airport",
                    "Indiana": "Indianapolis International Airport", "Iowa": "Des Moines International Airport",
                    "Kansas": "Garden City Regional Airport",
                    "Kentucky": "Blue Grass Airport",
                    "Louisiana": "Louis Armstrong New Orleans International Airport",
                    "Maine": "Bangor International Airport",
                    "Maryland": "Baltimore/Washington International Thurgood Marshal Airport",
                    "Massachusetts": "General Edward Lawrence Logan International Airport",
                    "Michigan": "Detroit Metropolitan Wayne County Airport",
                    "Minnesota": "Minneapolis-St Paul International/Wold-Chamberlain Airport",
                    "Mississippi": "Gulfport Biloxi International Airport",
                    "Missouri": "Lambert St Louis International Airport",
                    "Montana": "Glacier Park International Airport",
                    "Nebraska": "Eppley Airfield", "Nevada": "Harry Reid International Airport",
                    "New Hampshire": "Manchester Airport",
                    "New Jersey": "Trenton Mercer Airport", "New Mexico": "Albuquerque International Sunport",
                    "New York": "John F Kennedy International Airport",
                    "North Carolina": "Raleigh Durham International Airport",
                    "North Dakota": "Hector International Airport",
                    "Ohio": "Port Columbus International Airport", "Oklahoma": "Will Rogers World Airport",
                    "Oregon": "Portland International Airport",
                    "Pennsylvania": "Philadelphia International Airport",
                    "Rhode Island": "Theodore Francis Green State Airport",
                    "South Carolina": "Myrtle Beach International Airport",
                    "South Dakota": "Joe Foss Field Airport",
                    "Tennessee": "Nashville International Airport", "Texas": "Dallas Love Field",
                    "Utah": "Salt Lake City International Airport",
                    "Vermont": "Burlington International Airport", "Virginia": "Dulles International Airport",
                    "Washington": "Snohomish County (Paine Field) Airport",
                    "West Virginia": "Yeager Airport", "Wisconsin": "Dane County Regional Truax Field",
                    "Wyoming": "Jackson Hole Airport"}
